# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "028379a848cfb92752ade9ef6d51b969"
name = "plug-play"
application_url = "https://vulnerable-degree-growing-proposal.trycloudflare.com/"
embedded = true
handle = "pagefly-30"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_orders,read_products,read_themes,write_content,write_products,write_themes"

[app_proxy]
url = "https://vulnerable-degree-growing-proposal.trycloudflare.com/proxy"
prefix = "apps"
subpath = "smartrec"

[auth]
redirect_urls = [
  "https://vulnerable-degree-growing-proposal.trycloudflare.com/auth/callback",
  "https://vulnerable-degree-growing-proposal.trycloudflare.com/auth/shopify/callback",
  "https://vulnerable-degree-growing-proposal.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
